{
 "title": "Customer Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lscustomername", "label": "LS-CustomerName", "query": { "query": "label_values(ls_customer_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Prometheus availability",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "prometheus_ready", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Free Memory %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{ls_customer_name=\"$lscustomername\"}/node_memory_MemTotal_bytes{ls_customer_name=\"$lscustomername\"}*100",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Raid status of devices",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "node_md_state{ls_customer_name=\"$lscustomername\"}",
     "legendFormat": "{{device}}:{{state}}"
    }
   ]
  },
  {
   "title": "Free storage space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{ls_customer_name=\"$lscustomername\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}